### ISSUE TITLE
Codes Not Working

### ISSUE THREAD

**Issue by Anonymous42456** [Megabyte918/MK8-Cheat-Codes#1]
The codes don't work. MK8 is on v4.1 for me and it's digital and NTSC. I used JGecko U on my PC and installed CosmoCourtney's codehandler on the Wii U. I added 4 different codes and sent them. What am I doing wrong?

**Comment by m-byte918** [comment]
What happened when you sent the codes? Did you get an error on JGecko U? Did your Wii U happen to crash?

Also, which codes have you tested that have not worked? I will try to fix them.

**Comment by Anonymous42456** [comment]
Never mind. The codes do work. I just didn't have the latest version of TCPGecko. But the Item Hack code freezes my game.

**Comment by m-byte918** [comment]
Odd, it works fine for me. Make sure you aren't sending any codes in-between races (while the game is loading/unloading tracks) because memory regions tend to shift. If that doesn't work for you, try only sending the code once the track has loaded.

**Comment by Anonymous42456** [comment]
I did. When I started the race, I had a banana even though I'm supposed to have triple mushrooms and then the game freezes after 3-5 seconds in the race.

**Comment by Anonymous42456** [comment]
Here is how I set up the code

30000000 4443BB4C
35000000 50000000
05120000 00000075
00000000 00000000
C0000011 60000000
3C00FFFF 6000FFFF
3C40C044 60424BB7
3CC0FBFC 60C6FDFF
3C20EEFF 6021FF7F
7C021278 7C010A78
7C063278 80420000
80210000 38620044
90230000 38820054
38A00000 90A40000
38E2003C 80E70000
38E70028 90C70000
39000006 3922003C
81290000 39490044
39290048 910A0000
91090000 60000000
3C40010F 60426AE0
7C4903A6 4E800420
30000000 4443BB4C
35000000 50000000
05120000 00000075
00000000 00000000
09020000 102F48A8
10001000 00000000
00020000 11000080
0000000B 00000000
D0000000 DEADCAFE
09020000 102F48A8
10001000 00000000
00020000 11000080
0000000B 00000000
D0000000 DEADCAFE

**Comment by Anonymous42456** [comment]
I'm using 2 button combinations. D-Pad Up and Y. The item I'm trying to use is the Golden Mushroom. I'm using the Gamepad.

**Comment by Anonymous436** [comment]
Does the code only work online?

**Comment by Anonymous42456** [comment]
Am I entering the code wrong?

**Comment by m-byte918** [comment]
Try this. I removed the checks to see if the track has loaded or not, it might have been what made it crash (which is kind of ironic, considering it was put there to PREVENT crashes between loading screens, haha)

Make sure to only send it when the track is loaded and disable it once the race is over:
```
C0000011 60000000
3C00FFFF 6000FFFF
3C40C044 60424BB7
3CC0FBFC 60C6FDFF
3C20EEFF 6021FF7F
7C021278 7C010A78
7C063278 80420000
80210000 38620044
90230000 38820054
38A00000 90A40000
38E2003C 80E70000
38E70028 90C70000
39000006 3922003C
81290000 39490044
39290048 910A0000
91090000 60000000
3C40010F 60426AE0
7C4903A6 4E800420
09020000 XXXXXXXX
YYYYYYYY 00000000
00020000 11000080
000000ZZ 00000000
D0000000 DEADCAFE
09020000 XXXXXXXX
YYYYYYYY 00000000
00020000 11000080
000000ZZ 00000000
D0000000 DEADCAFE
```
Also make sure your button activators and values for those activators are correct. For the Wii U Gamepad controller address, Dpad Up is `00000200` and Y is `00001000`. So Dpad Up + Y would be `00001200`. If you are using the Pro Controller address, then Dpad Up is `00000001` and Y is `00000020`, so Dpad Up + Y is `00000021`.

Also, the code has two button activator slots to switch between different items.
```
09020000 XXXXXXXX <-- X's = controller address
YYYYYYYY 00000000 <-- Y's = Keypress to switch to item 1
00020000 11000080
000000ZZ 00000000 <-- Z's =  item 1
D0000000 DEADCAFE
09020000 XXXXXXXX <-- X's = controller address
YYYYYYYY 00000000 <-- Y's = Keypress to switch to item 2
00020000 11000080
000000ZZ 00000000 <-- Z's =  item 2
D0000000 DEADCAFE
```
So if you set both keypresses for item 1 & 2 to the same keypress, the code will either switch to one item and do nothing, or it will crash your Wii U. See [this list of button activators](https://github.com/Megabyte918/MK8-Memory-Notes/blob/master/ACTIVATORS.md) if you need help remembering.

**Comment by Anonymous42456** [comment]
I can have 2 items in one code?

**Comment by Anonymous42456** [comment]
My Wii U still crashed. But this time it crashed before I could even start the race.

**Comment by m-byte918** [comment]
Yes you can have 2 items in one code. Also that code works fine for me, can you show me how you set yours up?

**Comment by Anonymous42456** [comment]
30000000 4443BB4C
35000000 50000000
05120000 00000075
00000000 00000000
C0000011 60000000
3C00FFFF 6000FFFF
3C40C044 60424BB7
3CC0FBFC 60C6FDFF
3C20EEFF 6021FF7F
7C021278 7C010A78
7C063278 80420000
80210000 38620044
90230000 38820054
38A00000 90A40000
38E2003C 80E70000
38E70028 90C70000
39000006 3922003C
81290000 39490044
39290048 910A0000
91090000 60000000
3C40010F 60426AE0
7C4903A6 4E800420
30000000 4443BB4C
35000000 50000000
05120000 00000075
00000000 00000000
09020000 1F604EA0
00001200 00000000
00020000 11000080
0000000B 00000000
D0000000 DEADCAFE
09020000 1F604EA0
00001800 00000000
00020000 11000080
00000002 00000000
D0000000 DEADCAFE

**Comment by Anonymous42456** [comment]
Btw, I have the digital copy of MK8 if that matters at all.

**Comment by m-byte918** [comment]
@Anonymous436 Use the edited code I posted above.

**Comment by Anonymous42456** [comment]
But I did...

**Comment by m-byte918** [comment]
The code you've set up and pasted above is the code that does not work, The code I have pasted above has been confirmed to work, as long as you enable is once the race starts and disable it once the race ends. Make sure you are using the code that has the checks removed (the one I've pasted above). The one you are using still has the checks and that is why it is crashing.

>Try this. I removed the checks to see if the track has loaded or not, it might have been what made it crash (which is kind of ironic, considering it was put there to PREVENT crashes between loading screens, haha)
>
>Make sure to only send it when the track is loaded and disable it once the race is over:
>```
>C0000011 60000000
>3C00FFFF 6000FFFF
>3C40C044 60424BB7
>3CC0FBFC 60C6FDFF
>3C20EEFF 6021FF7F
>7C021278 7C010A78
>7C063278 80420000
>80210000 38620044
>90230000 38820054
>38A00000 90A40000
>38E2003C 80E70000
>38E70028 90C70000
>39000006 3922003C
>81290000 39490044
>39290048 910A0000
>91090000 60000000
>3C40010F 60426AE0
>7C4903A6 4E800420
>09020000 XXXXXXXX
>YYYYYYYY 00000000
>00020000 11000080
>000000ZZ 00000000
>D0000000 DEADCAFE
>09020000 XXXXXXXX
>YYYYYYYY 00000000
>00020000 11000080
>000000ZZ 00000000
>D0000000 DEADCAFE
>```

**Comment by Anonymous42456** [comment]
I don't get how the code is working for everyone but me.

**Comment by Anonymous42456** [comment]
Anyways, thank you for trying to help me.

**Comment by Anonymous42456** [comment]
I got the code working! Thanks again for your help.
