### ISSUE TITLE
Can't Get No Countdown/No Collisions to Work

### ISSUE THREAD

**Issue by Agent-9** [Megabyte918/MK8-Cheat-Codes#2]
I know this repository is pretty old by now, but I just can't get no countdown or no collisions to work. When I try to use no countdown, my character is unable to move for the rest of the race until I quit, and when I attempted to use no collisions my Wii U crashed. I only tested them offline.

Is this just because the codes are old? Or am I doing something wrong?

**Comment by m-byte918** [comment]
What version of Mario Kart 8 are you using? All of the codes have been tested and confirmed working on `v4.1, USA`.

**Comment by Agent-9** [comment]
I am running v4.1, but I figure it's probably not working because I'm using a European version of the game.

**Comment by m-byte918** [comment]
That is the reason why. There is a gap between memory locations in different regions of the game, you can get the code working for the European version if you figure out the length of the gap, and offset each memory location by that amount.
